root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"


[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -gcflags='all=-N -l' -o ./tmp/main ./cmd/server/main.go"
  full_bin = "dlv exec --accept-multiclient --log --headless --continue --listen :40000 --api-version 2 ./tmp/main"
  delay = 1000
  exclude_dir = ["go", "tmp", "vendor", "testdata"]



[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false