name: deoences-autoupdate

on: 
  schedule:
    - cron: '0 0 * * *' # every day at 00:00 UTC
  push:

jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the head commit of the branch
      uses: actions/checkout@v3

    - name: Go setup
      uses: actions/setup-go@v2

    - name: Run auto dependency update 
      uses: romoh/dependencies-autoupdate@v1
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
        update-command: "'go get -u && go mod tidy && go build'"